team-haribo/GOMS-Android

- presentation/src/main/AndroidManifest.xml
- presentation/src/main/java/com/goms/presentation/view/home/HomeFragment.kt
- presentation/src/main/java/com/goms/presentation/view/main/MainActivity.kt
- presentation/src/main/java/com/goms/presentation/view/outing/component/EmptyScreen.kt
- presentation/src/main/java/com/goms/presentation/view/profile/ProfileActivity.kt
- presentation/src/main/res/drawable/back_arrow_black.xml
- presentation/src/main/res/drawable/profile_card_background.xml
- presentation/src/main/res/layout/activity_profile.xml
- presentation/src/main/res/values/colors.xml
second gray color 이름 변경
profile screen 화면 구성
profile screen으로 이동하는 로직 추가
> 🔀 :: (#7) - profile screen 퍼블리싱

- presentation/src/main/java/com/goms/presentation/view/home/component/HomeItemCard.kt
- presentation/src/main/java/com/goms/presentation/view/outing/component/OutingStudentCard.kt
- presentation/src/main/res/layout/fragment_home.xml
home screen weight 조정
onClick 제거
> 🔀 :: (#13) - ui 리팩토링

- buildSrc/src/main/java/Dependency.kt
- buildSrc/src/main/java/Versions.kt
- presentation/build.gradle.kts
- presentation/src/main/AndroidManifest.xml
- presentation/src/main/java/com/goms/presentation/view/home/HomeFragment.kt
- presentation/src/main/java/com/goms/presentation/view/main/MainActivity.kt
- presentation/src/main/java/com/goms/presentation/view/qr_scan/QrScanFragment.kt
- presentation/src/main/java/com/goms/presentation/view/qr_scan/capture/QrCodeActivity.kt
- presentation/src/main/res/layout/activity_qr_code.xml
- presentation/src/main/res/layout/fragment_qr_scan.xml
qr code 화면 ui 구성
qr code 화면 기능 구현
QrCodeActivity와 화면 연결 로직 생성
> 🔀 :: (#15) - QR code 화면 생성

- buildSrc/src/main/java/Dependency.kt
- buildSrc/src/main/java/Versions.kt
- presentation/build.gradle.kts
- presentation/src/main/java/com/goms/presentation/view/main/MainActivity.kt
- presentation/src/main/res/layout/activity_main.xml
- presentation/src/main/res/menu/bottom_navi_item.xml
- presentation/src/main/res/navigation/bottom_navigation.xml
navigation graph 생성
bottom menu id 변경
navigation component 적용
> 🔀 :: (#17) - bottom navigation jetpack navigation 적용하기

- buildSrc/src/main/java/Dependency.kt
- buildSrc/src/main/java/Versions.kt
- data/src/main/java/com/goms/data/api/ProfileApi.kt
- data/src/main/java/com/goms/data/datasource/profile/ProfileDataSource.kt
- data/src/main/java/com/goms/data/datasource/profile/ProfileDataSourceImpl.kt
- data/src/main/java/com/goms/data/model/profile/response/StudentInfo.kt
- data/src/main/java/com/goms/data/repository/ProfileRepositoryImpl.kt
- domain/src/main/java/com/goms/domain/data/profile/response/StudentInfoData.kt
- domain/src/main/java/com/goms/domain/repository/ProfileRepository.kt
- domain/src/main/java/com/goms/domain/usecase/profile/ProfileUseCase.kt
- presentation/build.gradle.kts
- presentation/src/main/java/com/goms/presentation/di/module/DataSourceModule.kt
- presentation/src/main/java/com/goms/presentation/di/module/NetWorkModule.kt
- presentation/src/main/java/com/goms/presentation/di/module/RepositoryModule.kt
- presentation/src/main/java/com/goms/presentation/di/module/UseCaseModule.kt
- presentation/src/main/java/com/goms/presentation/view/home/HomeFragment.kt
- presentation/src/main/java/com/goms/presentation/view/main/MainActivity.kt
- presentation/src/main/java/com/goms/presentation/view/profile/ProfileActivity.kt
- presentation/src/main/java/com/goms/presentation/view/sign_in/SignInActivity.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/ProfileViewModel.kt
- presentation/src/main/res/layout/activity_profile.xml
- presentation/src/main/res/layout/fragment_home.xml
프로필 api 구성
main, profile, home 화면에 프로필 로직 추가
> 🔀 :: (#23) - 프로필 기능 구현

- data/src/main/java/com/goms/data/api/ProfileApi.kt
- data/src/main/java/com/goms/data/api/interceptor/LoginInterceptor.kt
- data/src/main/java/com/goms/data/datasource/profile/ProfileDataSource.kt
- data/src/main/java/com/goms/data/datasource/profile/ProfileDataSourceImpl.kt
- data/src/main/java/com/goms/data/repository/ProfileRepositoryImpl.kt
- domain/src/main/java/com/goms/domain/repository/ProfileRepository.kt
- domain/src/main/java/com/goms/domain/usecase/profile/ProfileUseCase.kt
- presentation/src/main/java/com/goms/presentation/di/module/UseCaseModule.kt
인터셉터에서 요청 보낼 떄마다 자동으로 header 추가해서 요청해주는 로직 추가
프로필 로직 파일에서 access token 파라미터 제거
> 🔀 :: (#25) - http 인터셉터 리팩토링

- domain/src/main/java/com/goms/domain/data/profile/response/ProfileResponseData.kt
- domain/src/main/java/com/goms/domain/data/profile/response/StudentInfoData.kt
- presentation/src/main/java/com/goms/presentation/view/home/HomeFragment.kt
- presentation/src/main/java/com/goms/presentation/view/main/MainActivity.kt
- presentation/src/main/java/com/goms/presentation/view/profile/ProfileActivity.kt
- presentation/src/main/java/com/goms/presentation/view/splash/SplashActivity.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/SignInViewModel.kt
- presentation/src/main/res/layout/activity_profile.xml
프로필 screen progress bar 제거
home screen, main activity에서 프로필 데이터 전달 기능 추가, 적용
> 🔀 :: (#27) - 프로필 데이터 전달 기능 핫픽스

- data/src/main/java/com/goms/data/api/ProfileApi.kt
- data/src/main/java/com/goms/data/api/interceptor/LoginInterceptor.kt
- data/src/main/java/com/goms/data/datasource/profile/ProfileDataSource.kt
- data/src/main/java/com/goms/data/datasource/profile/ProfileDataSourceImpl.kt
- data/src/main/java/com/goms/data/mapper/AuthMapper.kt
- data/src/main/java/com/goms/data/mapper/ProfileMapper.kt
- data/src/main/java/com/goms/data/model/profile/ProfileResponse.kt
- data/src/main/java/com/goms/data/model/profile/StudentInfo.kt
- data/src/main/java/com/goms/data/repository/AuthRepositoryImpl.kt
- domain/src/main/java/com/goms/domain/data/auth/request/SignInRequestData.kt
- domain/src/main/java/com/goms/domain/data/auth/response/SignInResponseData.kt
- domain/src/main/java/com/goms/domain/repository/AuthRepository.kt
- domain/src/main/java/com/goms/domain/usecase/auth/SignInUseCase.kt
- presentation/src/main/java/com/goms/presentation/view/splash/SplashActivity.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/SignInViewModel.kt
패키지 rename, delete
splash activity handler delay 추가
interceptor request 변수 rename
> 🔀 :: (#29) - 파일 구조 변경(핫픽스)

- buildSrc/src/main/java/Dependency.kt
- buildSrc/src/main/java/Versions.kt
- data/src/main/java/com/goms/data/api/OutingApi.kt
- data/src/main/java/com/goms/data/datasource/outing/OutingDataSource.kt
- data/src/main/java/com/goms/data/datasource/outing/OutingDataSourceImpl.kt
- data/src/main/java/com/goms/data/mapper/OutingMapper.kt
- data/src/main/java/com/goms/data/model/outing/OutingCountResponse.kt
- data/src/main/java/com/goms/data/repository/OutingRepositoryImpl.kt
- domain/src/main/java/com/goms/domain/data/outing/OutingCountResponseData.kt
- domain/src/main/java/com/goms/domain/repository/OutingRepository.kt
- domain/src/main/java/com/goms/domain/usecase/outing/OutingCountUseCase.kt
- domain/src/main/java/com/goms/domain/usecase/outing/OutingListUseCase.kt
- domain/src/main/java/com/goms/domain/usecase/outing/OutingUseCase.kt
- presentation/build.gradle.kts
- presentation/src/main/java/com/goms/presentation/di/module/DataSourceModule.kt
- presentation/src/main/java/com/goms/presentation/di/module/NetWorkModule.kt
- presentation/src/main/java/com/goms/presentation/di/module/RepositoryModule.kt
- presentation/src/main/java/com/goms/presentation/di/module/UseCaseModule.kt
- presentation/src/main/java/com/goms/presentation/view/home/HomeFragment.kt
- presentation/src/main/java/com/goms/presentation/view/main/MainActivity.kt
- presentation/src/main/java/com/goms/presentation/view/outing/OutingFragment.kt
- presentation/src/main/java/com/goms/presentation/view/outing/component/OutingStudentCard.kt
- presentation/src/main/java/com/goms/presentation/view/qr_scan/capture/QrCodeActivity.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/OutingViewModel.kt
outing sevice 생성, 구현
불필요한 로직 제거
tedPermission으로 권한 처리
> 🔀 :: (#31) - outing 로직 구현

- buildSrc/src/main/java/Dependency.kt
- buildSrc/src/main/java/Versions.kt
- data/src/main/java/com/goms/data/api/LateApi.kt
- data/src/main/java/com/goms/data/datasource/late/LateDataSource.kt
- data/src/main/java/com/goms/data/datasource/late/LateDataSourceImpl.kt
- data/src/main/java/com/goms/data/model/profile/ProfileResponse.kt
- data/src/main/java/com/goms/data/repository/LateRepositoryImpl.kt
- domain/src/main/java/com/goms/domain/repository/LateRepository.kt
- domain/src/main/java/com/goms/domain/usecase/late/LateUseCase.kt
- presentation/build.gradle.kts
- presentation/src/main/java/com/goms/presentation/di/module/DataSourceModule.kt
- presentation/src/main/java/com/goms/presentation/di/module/NetWorkModule.kt
- presentation/src/main/java/com/goms/presentation/di/module/RepositoryModule.kt
- presentation/src/main/java/com/goms/presentation/di/module/UseCaseModule.kt
- presentation/src/main/java/com/goms/presentation/view/home/HomeFragment.kt
- presentation/src/main/java/com/goms/presentation/view/home/component/HomeItemCard.kt
- presentation/src/main/java/com/goms/presentation/view/main/MainActivity.kt
- presentation/src/main/java/com/goms/presentation/view/outing/component/OutingStudentCard.kt
- presentation/src/main/java/com/goms/presentation/view/profile/ProfileActivity.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/LateViewModel.kt
- presentation/src/main/res/layout/activity_main.xml
- presentation/src/main/res/layout/activity_profile.xml
- presentation/src/main/res/layout/fragment_home.xml
지각 랭킹 기능 생성, 적용
circle image 적용
> 🔀 :: (#31) - 지각 랭킹 구현

- data/src/main/java/com/goms/data/api/interceptor/LoginInterceptor.kt
- data/src/main/java/com/goms/data/repository/AuthRepositoryImpl.kt
- presentation/src/main/java/com/goms/presentation/view/home/HomeFragment.kt
- presentation/src/main/java/com/goms/presentation/view/sign_in/SignInActivity.kt
- presentation/src/main/java/com/goms/presentation/view/splash/SplashActivity.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/OutingViewModel.kt
- presentation/src/main/res/layout/fragment_home.xml
로그인 여부 확인 코드 정리
외출 상태 관리 로직 추가, 적용
불필요한 데이터 전달 삭제
> 🔀 :: (#33) - 외출 상태 관리 로직 추가

- data/src/main/java/com/goms/data/api/OutingApi.kt
- data/src/main/java/com/goms/data/datasource/outing/OutingDataSource.kt
- data/src/main/java/com/goms/data/datasource/outing/OutingDataSourceImpl.kt
- data/src/main/java/com/goms/data/repository/OutingRepositoryImpl.kt
- domain/src/main/java/com/goms/domain/repository/OutingRepository.kt
- domain/src/main/java/com/goms/domain/usecase/outing/OutingUseCase.kt
- presentation/src/main/java/com/goms/presentation/view/qr_scan/capture/QrCodeActivity.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/OutingViewModel.kt
> 🔀 :: (#39) - 외출하기 로직 변경

- presentation/src/main/java/com/goms/presentation/view/profile/ProfileActivity.kt
프로필 screen의 user card에서 학번이 10 미만일때 0이 붙어서 출력되던 문제 해결
> 🔀 :: (#43) - 학번 이슈 수정

- data/src/main/java/com/goms/data/api/OutingApi.kt
- data/src/main/java/com/goms/data/datasource/outing/OutingDataSource.kt
- data/src/main/java/com/goms/data/datasource/outing/OutingDataSourceImpl.kt
- data/src/main/java/com/goms/data/mapper/UserMapper.kt
- data/src/main/java/com/goms/data/model/user/UserInfo.kt
- data/src/main/java/com/goms/data/model/user/UserResponse.kt
- data/src/main/java/com/goms/data/repository/OutingRepositoryImpl.kt
- domain/src/main/java/com/goms/domain/data/user/UserInfoData.kt
- domain/src/main/java/com/goms/domain/data/user/UserResponseData.kt
- domain/src/main/java/com/goms/domain/repository/OutingRepository.kt
- domain/src/main/java/com/goms/domain/usecase/outing/OutingListUseCase.kt
- presentation/src/main/java/com/goms/presentation/view/outing/OutingFragment.kt
- presentation/src/main/java/com/goms/presentation/view/outing/component/OutingStudentCard.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/OutingViewModel.kt
outing list 통신 부분 response type 변경
> 🔀 :: (#45) - 외출 list return type 변경

- data/src/main/java/com/goms/data/api/CouncilApi.kt
- data/src/main/java/com/goms/data/datasource/admin/CouncilDataSource.kt
- data/src/main/java/com/goms/data/datasource/admin/CouncilDataSourceImpl.kt
- data/src/main/java/com/goms/data/mapper/CouncilMapper.kt
- data/src/main/java/com/goms/data/model/council/ModifyRoleRequest.kt
- data/src/main/java/com/goms/data/repository/CouncilRepositoryImpl.kt
- domain/build.gradle.kts
- domain/src/main/java/com/goms/domain/data/council/ModifyRoleRequestData.kt
- domain/src/main/java/com/goms/domain/exception/HttpException.kt
- domain/src/main/java/com/goms/domain/exception/OtherException.kt
- domain/src/main/java/com/goms/domain/repository/CouncilRepository.kt
- domain/src/main/java/com/goms/domain/usecase/admin/ModifyRoleUseCase.kt
- presentation/src/main/java/com/goms/presentation/di/module/UseCaseModule.kt
- presentation/src/main/java/com/goms/presentation/view/manage/StudentManageActivity.kt
- presentation/src/main/java/com/goms/presentation/view/manage/component/StudentManageCard.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/CouncilViewModel.kt
- presentation/src/main/res/layout/activity_student_manage.xml
domain애 dependency 추가
학생 권한 수정 기능 생성, 구현
> 🔀 :: (#51) - 학생 권한 수정 기능 구현

- domain/src/main/java/com/goms/domain/exception/HttpException.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/LateViewModel.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/OutingViewModel.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/ProfileViewModel.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/SignInViewModel.kt
custom exception 생성
view model의 http response가 fail일 때 exception throw 되게 변
> 🔀 :: (#53) - http 통신 response 실패 시 로직 변경

- data/src/main/java/com/goms/data/api/CouncilApi.kt
- data/src/main/java/com/goms/data/datasource/admin/CouncilDataSource.kt
- data/src/main/java/com/goms/data/datasource/admin/CouncilDataSourceImpl.kt
- data/src/main/java/com/goms/data/repository/CouncilRepositoryImpl.kt
- domain/src/main/java/com/goms/domain/repository/CouncilRepository.kt
- domain/src/main/java/com/goms/domain/usecase/admin/SetBlackListUseCase.kt
- presentation/src/main/java/com/goms/presentation/di/module/UseCaseModule.kt
- presentation/src/main/java/com/goms/presentation/view/manage/StudentManageActivity.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/CouncilViewModel.kt
> 🔀 :: (#55) - 외출 금지 기능 구현

- buildSrc/src/main/java/Dependency.kt
- buildSrc/src/main/java/Versions.kt
- data/src/main/java/com/goms/data/api/CouncilApi.kt
- data/src/main/java/com/goms/data/datasource/admin/CouncilDataSource.kt
- data/src/main/java/com/goms/data/datasource/admin/CouncilDataSourceImpl.kt
- data/src/main/java/com/goms/data/model/council/response/MakeQrCodeResponse.kt
- data/src/main/java/com/goms/data/repository/CouncilRepositoryImpl.kt
- domain/src/main/java/com/goms/domain/data/council/response/MakeQrCodeResponseData.kt
- domain/src/main/java/com/goms/domain/exception/HttpException.kt
- domain/src/main/java/com/goms/domain/repository/CouncilRepository.kt
- domain/src/main/java/com/goms/domain/usecase/admin/MakeQrCodeUseCase.kt
- presentation/build.gradle.kts
- presentation/src/main/java/com/goms/presentation/di/module/UseCaseModule.kt
- presentation/src/main/java/com/goms/presentation/view/profile/ProfileActivity.kt
- presentation/src/main/java/com/goms/presentation/view/qr_scan/QrScanFragment.kt
- presentation/src/main/java/com/goms/presentation/view/qr_scan/capture/QrCodeActivity.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/CouncilViewModel.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/OutingViewModel.kt
- presentation/src/main/res/layout/activity_profile.xml
- presentation/src/main/res/layout/activity_student_manage.xml
- presentation/src/main/res/layout/fragment_qr_scan.xml
zxing 라이브러리 추가
qr 코드 생성 로직 생성, 구현
일부 ui의 구성 살짝 변경
외출 로직에서 예외 처리 로직 생성
> 🔀 :: (#61) - qr code 생성 로직 구현

- domain/src/main/java/com/goms/domain/usecase/admin/SetBlackListUseCase.kt
- presentation/src/main/java/com/goms/presentation/utils/GomsDialog.kt
- presentation/src/main/java/com/goms/presentation/view/manage/bottomsheet/ModifyRoleBottomSheetDialog.kt
- presentation/src/main/java/com/goms/presentation/view/profile/ProfileActivity.kt
- presentation/src/main/res/drawable/dialog_bg.xml
- presentation/src/main/res/drawable/dialog_button_bg_no.xml
- presentation/src/main/res/layout/goms_dialog.xml
> 🔀 :: (#63) - goms custom dialog 구현

- data/src/main/java/com/goms/data/api/CouncilApi.kt
- data/src/main/java/com/goms/data/datasource/admin/CouncilDataSource.kt
- data/src/main/java/com/goms/data/datasource/admin/CouncilDataSourceImpl.kt
- data/src/main/java/com/goms/data/mapper/CouncilMapper.kt
- data/src/main/java/com/goms/data/model/council/response/UserListResponse.kt
- data/src/main/java/com/goms/data/repository/CouncilRepositoryImpl.kt
- domain/src/main/java/com/goms/domain/data/council/response/UserListResponseData.kt
- domain/src/main/java/com/goms/domain/repository/CouncilRepository.kt
- domain/src/main/java/com/goms/domain/usecase/admin/UserListUseCase.kt
- presentation/src/main/java/com/goms/presentation/view/manage/StudentManageActivity.kt
- presentation/src/main/java/com/goms/presentation/view/manage/component/StudentManageCard.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/CouncilViewModel.kt
- presentation/src/main/res/values/colors.xml
기존 학생 리스트 데이터 추가해 새로 생성
기존 get user list 로직 새로운 학생 리스트 data로 변경
user의 역할에 따른 역할(학생회, 외출 금지) text 생성 로직 구현
> 🔀 :: (#67) - 학생 리스트 api data response 변경

- data/src/main/java/com/goms/data/api/CouncilApi.kt
- data/src/main/java/com/goms/data/datasource/admin/CouncilDataSource.kt
- data/src/main/java/com/goms/data/datasource/admin/CouncilDataSourceImpl.kt
- data/src/main/java/com/goms/data/mapper/CouncilMapper.kt
- data/src/main/java/com/goms/data/model/council/response/SearchStudentResponse.kt
- data/src/main/java/com/goms/data/repository/CouncilRepositoryImpl.kt
- domain/src/main/java/com/goms/domain/data/council/response/SearchStudentResponseData.kt
- domain/src/main/java/com/goms/domain/repository/CouncilRepository.kt
- domain/src/main/java/com/goms/domain/usecase/admin/SearchStudentUseCase.kt
- presentation/src/main/java/com/goms/presentation/view/manage/StudentManageActivity.kt
- presentation/src/main/java/com/goms/presentation/view/manage/bottomsheet/SearchFilterBottomSheetDialog.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/CouncilViewModel.kt
- presentation/src/main/res/layout/bottom_sheet_search_filter.xml
사용자 검색 api isBlackList data 추가
사용자 검색 로직에 null safety 추가
검색 filter UI 초기 상태 전부 선택되지 않음으로 설정
검색 filter에 확장된 검색 기능 구현(빈 값 허용)
> 🔀 :: (#69) - 검색 filter 검색 조건 확장

- .github/workflows/android.yml
> 🔀 :: (#71) - ci 세팅

- presentation/src/main/res/layout/fragment_qr_scan.xml
qr scan 화면 ui 재구성
화면에 갱신까지 남은 시간을 알 수 있는 timer 생성
textView, Space 추가
> 🔀 :: (#78) - qr scan 재퍼블리싱

- presentation/src/main/AndroidManifest.xml
화면을 가로 모드로 변경 시 카메라가 켜지는 오류 발생
화면을 가로 모드로 변경을 못하게 막기
manifest 파일에 화면 고정 추가
> 🔀 :: (#80) - 화면 전환 시 에러 수정

- presentation/src/main/java/com/goms/presentation/view/qr_scan/QrScanFragment.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/CouncilViewModel.kt
- presentation/src/main/res/layout/fragment_qr_scan.xml
- QR 생성하고 5분 지날 시 QR 재생성하기
- 타이머 세팅하기
- 타이머 시간이 0초가 될 시 QR 재생성하기
> 🔀 :: (#85) add qr timer

- presentation/src/main/java/com/goms/presentation/view/home/HomeFragment.kt
- presentation/src/main/java/com/goms/presentation/view/splash/SplashActivity.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/OutingViewModel.kt
외출/복귀에 따른 button text가 변경되지 않았음
잘못되었던 sharedPreference key, 조건 수정
잘못된 위치에서 호출되던 함수 수정
sharedPreference 조건, key 변경
함수 호출 부분 변경
> 🔀 :: (#91) - 외출 상태에 따라 button 텍스트 달라지지 않던 오류 수정

- presentation/src/main/AndroidManifest.xml
- presentation/src/main/java/com/goms/presentation/view/home/HomeFragment.kt
- presentation/src/main/java/com/goms/presentation/view/manage/StudentManageActivity.kt
- presentation/src/main/java/com/goms/presentation/view/outing/OutingFragment.kt
- presentation/src/main/java/com/goms/presentation/view/qr_scan/QrScanFragment.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/CouncilViewModel.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/LateViewModel.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/OutingViewModel.kt
- presentation/src/main/res/layout/activity_student_manage.xml
- presentation/src/main/res/layout/fragment_home.xml
- presentation/src/main/res/layout/fragment_outing.xml
- presentation/src/main/res/layout/fragment_qr_scan.xml
- presentation/src/main/res/layout/view_loading_indicator.xml
로딩 인디케이터가 빠져 앱이 미완성되어 보임
로딩 인디케이터 추가
loading indicator xml 생성
viewmodel에 로딩 상태 관리 로직 생성
screen(home, qr scan, outing, student manage)에 로딩 추가
> 🔀 :: (#90) - 로딩 인디케이터 생성

- buildSrc/src/main/java/Dependency.kt
- buildSrc/src/main/java/Versions.kt
- presentation/build.gradle.kts
- presentation/src/main/java/com/goms/presentation/view/manage/StudentManageActivity.kt
- presentation/src/main/res/layout/activity_student_manage.xml
- 관리자 학생 리스트에서 권한을 수정해도 리스트가 변화가 없었다
- 사용자가 Swipe 이벤트를 발생 시 학생 리스트를 재호출 했다.
- 시연 영상
https://github.com/team-goms/GOMS-Android/assets/84944098/24ec6276-2b78-4514-a08c-df712cd67375
> 🔀 :: (#86) updating when lazycolumn items change

- data/src/main/java/com/goms/data/datasource/outing/OutingDataSource.kt
- data/src/main/java/com/goms/data/datasource/outing/OutingDataSourceImpl.kt
- data/src/main/java/com/goms/data/repository/OutingRepositoryImpl.kt
- domain/src/main/java/com/goms/domain/exception/HttpException.kt
- domain/src/main/java/com/goms/domain/repository/OutingRepository.kt
- domain/src/main/java/com/goms/domain/usecase/outing/OutingUseCase.kt
- presentation/src/main/java/com/goms/presentation/utils/ApiErrorHandling.kt
- presentation/src/main/java/com/goms/presentation/view/home/HomeFragment.kt
- presentation/src/main/java/com/goms/presentation/view/main/MainActivity.kt
- presentation/src/main/java/com/goms/presentation/view/manage/StudentManageActivity.kt
- presentation/src/main/java/com/goms/presentation/view/outing/OutingFragment.kt
- presentation/src/main/java/com/goms/presentation/view/qr_scan/QrScanFragment.kt
- presentation/src/main/java/com/goms/presentation/view/qr_scan/capture/QrCodeActivity.kt
- presentation/src/main/java/com/goms/presentation/view/sign_in/SignInActivity.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/OutingViewModel.kt
- presentation/src/main/res/layout/fragment_qr_scan.xml
api 통신 할때 예외를 처리하기 위함
api 통신 부분 예외 처리
api 통신 부분에 try catch로 예외 처리 구문 추가
> 🔀 :: (#104) - api 통신 시 에러 handling

- presentation/src/main/java/com/goms/presentation/view/qr_scan/QrScanFragment.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/CouncilViewModel.kt
- qr 타이머 중첩 문제 발생
- 중첩 타이머 해결 하기
- qr 갱신 문제 해결 하기 (타이머 변경)
> 🔀 :: (#106) nested qr timer

- presentation/src/main/java/com/goms/presentation/view/qr_scan/QrScanFragment.kt
- qr uuid 갱신 문제 해결하기
- runCatching으로 에러처리하기
> 🔀 :: (#113) renew qr uuid

- presentation/src/main/res/layout/fragment_home.xml
휴대 전화의 크기에 따라 ***학생 관리하기***의 text가 잘리는 기기가 있었음
학생 관리하기 text 잘리던 오류 수정
> 🔀 :: (#133) - 학생 관리하기 text 잘리던 문제 해결

- data/build.gradle.kts
- domain/build.gradle.kts
- presentation/build.gradle.kts
- presentation/src/main/java/com/goms/presentation/view/qr_scan/QrScanFragment.kt
- presentation/src/main/java/com/goms/presentation/view/sign_in/SignInActivity.kt
- presentation/src/main/res/layout/activity_profile.xml
- presentation/src/main/res/layout/activity_sign_in.xml
- presentation/src/main/res/layout/fragment_home.xml
- presentation/src/main/res/layout/fragment_qr_scan.xml
- 태블릿에서 사용할 수 있게 업데이트
- 자잘한 이슈 고치기
- 태블릿에서도 사용가능하게 minSdk 30 -> 29로 내리기
- iOS랑 qr 스캔 부분중 다른 url 고치기
- 다크모드에 이상해지던 텍스트 색깔들 수정하기
- 로그아웃후 뒤로가기시 메인화면으로 오던 에러 고치기
> 🔀 :: (#143) 1.0.3 업데이트

- presentation/src/main/java/com/goms/presentation/view/manage/StudentManageActivity.kt
- presentation/src/main/java/com/goms/presentation/view/manage/bottomsheet/SearchFilterBottomSheetDialog.kt
- presentation/src/main/java/com/goms/presentation/view/manage/data/UserFilterOptions.kt
- presentation/src/main/java/com/goms/presentation/view/splash/SplashActivity.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/CouncilViewModel.kt
관리자 필터에서 검색한 후 새로고침이 되지 않던 오류 수정
불필요한 splash 코드 삭제
viewModel에 loading 체크 로직 추가
사용자의 필터 검색 정보를 저장할 data class 생성
사용자 필터 정보를 저장해 새로고침 할때 사용
> 🔀 :: (#149) - 관리자 필터가 새로고침되지 않던 오류 수정

- .idea/misc.xml
- presentation/src/main/java/com/goms/presentation/view/manage/bottomsheet/SearchFilterBottomSheetDialog.kt
필터 초기화를 눌렀을 때 선택된 값이 남아있던 오류 수정
초기화를 누르면 선택값을 저장하는 변수를 초기화하는 코드 작성
> 🔀 :: (#156) - 필터 초기화를 눌렀을 때 선택되었던 값이 남아있던 오류 수정

- presentation/src/main/java/com/goms/presentation/view/outing/OutingFragment.kt
- presentation/src/main/res/layout/fragment_outing.xml
새로고침후 LazyColumm 을 다시 PullScroll 하면 refresh로 고정되던 오류
새로고침후 LazyColumm 을 다시 PullScroll 하면 refresh로 고정되던 오류를 LazyColumn자체에서 refresh를 해버리게 OutingLazyColumn 함수안에 refresh로직을 추가했습니다
getOutingList() 함수를 suspend에서 함수 내부에서 CoroutineScope를 사용하게 재작성하여 suspend를 제거하였습니다.
제가 잘못 구현한 코드나 컨벤션에 맞지 않는 부분, 아쉬운 코드가 있다면 리뷰해주세요!
> 🔀 :: (#165) LazyColumn PullScroll 고정 오류 해결

- presentation/src/main/java/com/goms/presentation/view/outing/OutingFragment.kt
- presentation/src/main/java/com/goms/presentation/view/outing/component/OutingStudentCard.kt
- 외출 삭제 아이콘을 어드민에게만 보이도록 설정
- 어드민이 아닐 경우 외출 삭제 아이콘이 보이지 않음
> 🔀 :: (#161) - 외출 삭제 아이콘은 어드민에게만 보임

- presentation/src/main/java/com/goms/presentation/view/outing/OutingFragment.kt
- 외출리스트에서 학생을 삭제했을 시 즉시 적용됨
- 학생을 삭제할 때 리스트를 즉시 받아와 적용시킴
> 🔀 :: (#168) - 외출리스트에서 학생을 삭제 했을때 즉시 적용

- presentation/build.gradle.kts
- presentation/src/main/java/com/goms/presentation/view/splash/SplashActivity.kt
1.1.1 출시하기
- 앱 실행 시 실행이 정상적으로 이루어지지 않던 오류 수정
> 🔀 :: (#175) 1.1.1 출시

- data/src/main/java/com/goms/data/api/NotificationApi.kt
- data/src/main/java/com/goms/data/datasource/notification/NotificationDataSource.kt
- data/src/main/java/com/goms/data/datasource/notification/NotificationDataSourceImpl.kt
- data/src/main/java/com/goms/data/repository/NotificationRepositoryImpl.kt
- domain/src/main/java/com/goms/domain/repository/NotificationRepository.kt
- domain/src/main/java/com/goms/domain/usecase/notification/SetNotificationUseCase.kt
- presentation/build.gradle.kts
- presentation/src/main/AndroidManifest.xml
- presentation/src/main/java/com/goms/presentation/di/module/DataSourceModule.kt
- presentation/src/main/java/com/goms/presentation/di/module/NetWorkModule.kt
- presentation/src/main/java/com/goms/presentation/di/module/RepositoryModule.kt
- presentation/src/main/java/com/goms/presentation/di/module/UseCaseModule.kt
- presentation/src/main/java/com/goms/presentation/utils/notification/GomsNotification.kt
- presentation/src/main/java/com/goms/presentation/view/sign_in/SignInActivity.kt
- presentation/src/main/java/com/goms/presentation/view/splash/SplashActivity.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/NotificationViewModel.kt
- 곰스 푸시 알림 구현
- firebase message 초기화 작업을 로그인 되었을 때와 그렇지 않을 때를 구분하기 위해 splash와 sign in screen에 따로 firebase message service를 초기화 해주었음.
- firebase dependency 추가
- firebase message service 생성, manifest에 추가
- message service 초기화 로직 구현(splash, signin)
> 🔀 :: (#178) push notification 구현

- buildSrc/src/main/java/Dependency.kt
- buildSrc/src/main/java/Versions.kt
- data/src/main/java/com/goms/data/api/interceptor/LoginInterceptor.kt
- presentation/build.gradle.kts
- presentation/src/main/AndroidManifest.xml
- presentation/src/main/java/com/goms/presentation/view/main/MainActivity.kt
- presentation/src/main/java/com/goms/presentation/view/qr_scan/capture/QrCodeActivity.kt
- presentation/src/main/java/com/goms/presentation/view/splash/SplashActivity.kt
- notification permission request dialog 구현
- firebase 버전 업
- interceptor 수정
- notification request 구현
> 🔀 :: (#180) notification permission request dialog 구현

- buildSrc/src/main/java/Dependency.kt
- buildSrc/src/main/java/Versions.kt
- presentation/build.gradle.kts
- presentation/src/main/java/com/goms/presentation/view/splash/SplashActivity.kt
- goms 앱 업데이트 되어 있지 않을 때, 앱을 update하도록 하는 기능 구현
- in app update library를 이용해 구현함
- in app update dependency 추가
- splash에 update screen 띄우는 기능 구현
> 🔀 :: (#182) update 화면 기능 구현

- domain/src/main/java/com/goms/domain/exception/HttpException.kt
- presentation/src/main/java/com/goms/presentation/utils/ApiErrorHandling.kt
- presentation/src/main/java/com/goms/presentation/utils/dialog/GomsDialog.kt
- presentation/src/main/java/com/goms/presentation/utils/dialog/GomsNetworkDialog.kt
- presentation/src/main/java/com/goms/presentation/view/home/HomeFragment.kt
- presentation/src/main/java/com/goms/presentation/view/home/dialog/GomsBlackListDialog.kt
- presentation/src/main/java/com/goms/presentation/view/main/MainActivity.kt
- presentation/src/main/java/com/goms/presentation/view/manage/StudentManageActivity.kt
- presentation/src/main/java/com/goms/presentation/view/manage/bottomsheet/ModifyRoleBottomSheetDialog.kt
- presentation/src/main/java/com/goms/presentation/view/manage/bottomsheet/SearchFilterBottomSheetDialog.kt
- presentation/src/main/java/com/goms/presentation/view/outing/OutingFragment.kt
- presentation/src/main/java/com/goms/presentation/view/profile/ProfileActivity.kt
- presentation/src/main/java/com/goms/presentation/view/qr_scan/QrScanFragment.kt
- presentation/src/main/java/com/goms/presentation/view/qr_scan/capture/QrCodeActivity.kt
- presentation/src/main/java/com/goms/presentation/view/sign_in/SignInActivity.kt
- presentation/src/main/java/com/goms/presentation/view/splash/SplashActivity.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/CouncilViewModel.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/LateViewModel.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/NotificationViewModel.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/OutingViewModel.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/ProfileViewModel.kt
- presentation/src/main/java/com/goms/presentation/viewmodel/SignInViewModel.kt
- presentation/src/main/res/layout/goms_network_dialog.xml
- 네트워크가 불안정할 떄의 처리 구현
- 네트워크가 불안정할 때 띄울 dialog, exception 생성
- 특정 exception(UnknownHostException, SocketTimeoutException)이 발생할 경우 생성한 exception이 throw 되게 하는 로직 추가
- 생성한 exception이 throw 되었을 때, dialog를 띄우는 로직 추가(중복으로 발생하지 않게 하는 로직도 생성)
- viewmodel에서 apiErrorHandling 로직이 수행되게 변경
- 기존의 ui 화면에서 수행되던 apiErrorHandling 삭제
> 🔀 :: (#144) network가 불안정할 때의 처리

- presentation/build.gradle.kts
> 🔀 :: (#190) 서버 이전

- presentation/build.gradle.kts
> 🔀 :: (#191) 서버 이전(version: 1.2.3)

- presentation/build.gradle.kts
> 🔀 :: (#193) 1.2.3 출시

- presentation/build.gradle.kts
- presentation/src/main/java/com/goms/presentation/view/splash/SplashActivity.kt
- 서버 url 문제 고치기
- 불필요한 handler 삭제
release apk로 테스트한 서버 버전
> 🔀 :: (#195) fix server url

- presentation/build.gradle.kts
- presentation/src/main/java/com/goms/presentation/view/splash/SplashActivity.kt
> 🔀 :: (#197) 1.2.4 출시

- presentation/build.gradle.kts
> 🔀 :: (#198) 버전 업그레이드(1.2.5)

- presentation/build.gradle.kts
- 버전 업
- 깃허브 환경 변수 local properties 변경
> 🔀 :: (#199) 버전 업그레이드(1.2.6)

- presentation/build.gradle.kts
- 서버 url 변경
- local.properties BASE_URL 변경
> 🔀 :: (#200) change server url

- presentation/build.gradle.kts
- 버전 업
- local.properties BASE_URL 변경
> 🔀 :: (#201) 버전 업그레이드(1.2.7) 

- presentation/build.gradle.kts
- 서버 url 재변경
- local.properties BASE_URL 재변경
> 🔀 :: (#203) change server url again
